---
- name: start-nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"

- name: reload-nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded
  ignore_errors: "{{ ansible_check_mode }}"